logging:
  config: classpath:logback/logback-dev.xml
  level:
    nil:
      ed:
        chatroom:
          mapper: debug
spring:
  resources:
    static-locations: classpath:/static
  mvc:
    static-path-pattern: /chatroom/**
  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: src/main/java #重启目录
      exclude: WEB-INF/**
  redis:
    host: localhost
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/chatroom?useSSL=false&characterEncoding=UTF-8&useUnicode=true&serverTimezone=GMT-8&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    druid:
      initial-size: 8
      min-idle: 1
      max-active: 20
      max-wait: 60000
      time-between-eviction-runsMillis: 60000
      min-evictable-idle-timeMillis: 300000
      validation-query: select 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      use-global-data-source-stat: true

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  base-packages: nil.ed.chatroom.mapper